# Generated by Django 2.2.5 on 2019-10-23 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(default=datetime.datetime(2019, 10, 23, 18, 1, 11, 169687), max_length=50)),
                ('long', models.TextField()),
                ('by_user', models.CharField(max_length=150)),
                ('publsh', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
