# Generated by Django 2.2.5 on 2019-10-23 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='by_user',
        ),
        migrations.AlterField(
            model_name='link',
            name='short',
            field=models.CharField(default=datetime.datetime(2019, 10, 23, 18, 40, 52, 322686), max_length=50),
        ),
    ]
